package com.equipo2.Appkademy.rest.error;

public class ErrorCodes {

    //COMMON
    public static final String USER_ID_CANNOT_BE_NULL = "USER_ID_CANNOT_BE_NULL";
    public static final String EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED";

    public static final String USER_ID_IS_ALREADY_ATTACHED_TO_ANOTHER_ENTITY = "USER_ID_IS_ALREADY_ATTACHED_TO_ANOTHER_ENTITY";



    //TEACHER
    public static final String HOURLY_RATES_CANNOT_BE_NULL_OR_EMPTY = "HOURLY_RATES_CANNOT_BE_NULL_OR_EMPTY";
    public static final String FIRST_NAME_CANNOT_BE_NULL_OR_EMPTY = "FIRST_NAME_CANNOT_BE_NULL_OR_EMPTY";
    public static final String LAST_NAME_CANNOT_BE_NULL_OR_EMPTY = "LAST_NAME_CANNOT_BE_NULL_OR_EMPTY";
    public static final String EMAIL_CANNOT_BE_NULL_OR_EMPTY = "EMAIL_CANNOT_BE_NULL_OR_EMPTY";

    public static final String SHORT_DESCRIPTION_CANNOT_BE_NULL_OR_EMPTY = "EMAIL_CANNOT_BE_NULL_OR_EMPTY";

    public static final String FULL_DESCRIPTION_CANNOT_BE_NULL_OR_EMPTY = "FULL_DESCRIPTION_CANNOT_BE_NULL_OR_EMPTY";
    public static final String ADDRESS_CANNOT_BE_NULL = "ADDRESS_CANNOT_BE_NULL";

    public static final String MODALITIES_CANNOT_BE_NULL_OR_EMPTY = "MODALITIES_CANNOT_BE_NULL_OR_EMPTY";
    public static final String PROFICIENCIES_CANNOT_BE_NULL_OR_EMPTY = "PROFICIENCIES_CANNOT_BE_NULL_OR_EMPTY";
    public static final String WEEKLY_WORKING_SCHEDULE_CANNOT_BE_NULL = "WEEKLY_WORKING_SCHEDULE_CANNOT_BE_NULL";

    public static final String COUNTRY_CANNOT_BE_NULL_OR_EMPTY = "COUNTRY_CANNOT_BE_NULL_OR_EMPTY";

    public static final String PROVINCE_CANNOT_BE_NULL_OR_EMPTY = "PROVINCE_CANNOT_BE_NULL_OR_EMPTY";

    public static final String CITY_CANNOT_BE_NULL_OR_EMPTY = "CITY_CANNOT_BE_NULL_OR_EMPTY";

    public static final String STREET_NAME_CANNOT_BE_NULL_OR_EMPTY = "STREET_NAME_CANNOT_BE_NULL_OR_EMPTY";

    public static final String STREET_NUMBER_CANNOT_BE_NULL_OR_EMPTY = "STREET_NUMBER_CANNOT_BE_NULL_OR_EMPTY";

    public static final String CHECK_IN_CANNOT_BE_NULL = "CHECK_IN_CANNOT_BE_NULL";

    public static final String CHECK_OUT_CANNOT_BE_NULL = "CHECK_OUT_CANNOT_BE_NULL";

    public static final String STARTS_ON_CANNOT_BE_NULL = "STARTS_ON_CANNOT_BE_NULL";

    public static final String ENDS_ON_CANNOT_BE_NULL = "ENDS_ON_CANNOT_BE_NULL";

    public static final String PROVIDER_ID_CANNOT_BE_NULL = "PROVIDER_ID_CANNOT_BE_NULL";

    public static final String CUSTOMER_ID_CANNOT_BE_NULL = "CUSTOMER_ID_CANNOT_BE_NULL";
    public static final String TEACHER_WITH_SAME_EMAIL_ALREADY_EXISTS = "TEACHER_WITH_SAME_EMAIL_ALREADY_EXISTS";

    public static final String EMAIL_IS_NOT_VALID = "EMAIL_IS_NOT_VALID";

    public static final String TEACHING_SUBJECT_NAME_NOT_FOUND = "TEACHING_SUBJECT_NAME_NOT_FOUND";

    public static final String AT_LEAST_ONE_PROFICIENCY_DOESNT_EXIST = "AT_LEAST_ONE_PROFICIENCY_DOESNT_EXIST";

    public static final String TEACHER_NOT_FOUND = "TEACHER_NOT_FOUND";




    //STUDENT
    public static final String STUDENT_WITH_SAME_EMAIL_ALREADY_EXISTS = "STUDENT_WITH_SAME_EMAIL_ALREADY_EXISTS";
    public static final String STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND";

    //SCHEDULED APPOINTMENT
    public static final String SCHEDULED_APPOINTMENT_START_DATE_CANNOT_BE_IN_THE_PAST = "SCHEDULED_APPOINTMENT_START_DATE_CANNOT_BE_IN_THE_PAST";
    public static final String SCHEDULED_APPOINTMENT_END_DATE_CANNOT_BE_IN_THE_PAST = "SCHEDULED_APPOINTMENT_END_DATE_CANNOT_BE_IN_THE_PAST";
    public static final String SCHEDULED_APPOINTMENT_END_DATE_CANNOT_BE_BEFORE_START_DATE = "SCHEDULED_APPOINTMENT_END_DATE_CANNOT_BE_BEFORE_START_DATE";
    public static final String TEACHER_ALREADY_HAS_AN_OVERLAPPING_SCHEDULED_APPOINTMENT_ON_THIS_TIMEFRAME = "TEACHER_ALREADY_HAS_AN_OVERLAPPING_SCHEDULED_APPOINTMENT_ON_THIS_TIMEFRAME";
    public static final String APPOINTMENT_CANNOT_LAST_MORE_THAN_8_HOURS = "APPOINTMENT_CANNOT_LAST_MORE_THAN_8_HOURS";
    public static final String TEACHER_DOES_NOT_WORK_ON_APPOINTMENT_DAY = "TEACHER_DOES_NOT_WORK_ON_APPOINTMENT_DAY";
    public static final String APPOINTMENT_CANNOT_START_BEFORE_TEACHER_CHECK_IN_HOUR = "APPOINTMENT_CANNOT_START_BEFORE_TEACHER_CHECK_IN_HOUR";
    public static final String APPOINTMENT_CANNOT_END_AFTER_TEACHER_CHECK_OUT_HOUR = "APPOINTMENT_CANNOT_END_AFTER_TEACHER_CHECK_OUT_HOUR";
    public static final String HOURLY_RATES_VALUES_CANNOT_BE_NEGATIVE_OR_ZERO = "HOURLY_RATES_VALUES_CANNOT_BE_NEGATIVE_OR_ZERO";
    public static final String SCHEDULED_APPOINTMENT_NOT_FOUND = "SCHEDULED_APPOINTMENT_NOT_FOUND";



    // SECURITY
    public static final String MINIMUM_PASSSWORD_LENGTH_IS_7_CHARACTERS = "MINIMUM_PASSSWORD_LENGTH_IS_7_CHARACTERS";
    public static final String USER_NOT_FOUND = "USER_NOT_FOUND";

    // CHARACTERISTIC
    public static final String CHARACTERISTIC_ICON_CANNOT_BE_NULL_OR_EMPTY = "CHARACTERISTIC_ICON_CANNOT_BE_NULL_OR_EMPTY";
    public static final String CHARACTERISTIC_NAME_CANNOT_BE_NULL_OR_EMPTY = "CHARACTERISTIC_NAME_CANNOT_BE_NULL_OR_EMPTY";
    public static final String AT_LEAST_ONE_CHARACTERISTIC_IN_CREATE_REQUEST_DTO_DOESNT_EXISTS = "AT_LEAST_ONE_CHARACTERISTIC_IN_CREATE_REQUEST_DTO_DOESNT_EXISTS";

    public static final String CHARACTERISTIC_NOT_FOUND = "CHARACTERISTIC_NOT_FOUND";

    // UPLOAD
    public static final String ONLY_JPEG_OR_PNG_FILE_EXTENSION_ALLOWED = "ONLY_JPEG_OR_PNG_FILE_EXTENSION_ALLOWED";
    public static final String UNKOWN_ERROR_WHILE_UPLOADING_FILE = "UNKOWN_ERROR_WHILE_UPLOADING_FILE";
}
