stages:
  - build_frontend
  - deploy_frontend

cache:
  paths:
    - frontend/node_modules/

before_script_frontend:
  stage: build_frontend
  image: node:14
  script:
    - cd frontend
    - npm install
  artifacts:
    paths:
      - frontend/node_modules/

build_frontend:
  stage: build_frontend
  image: node:14
  script:
    - cd frontend
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

deploy_frontend:
  stage: deploy_frontend
  image: python:3.8
  before_script:
    - apt-get update && apt-get install -y awscli
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync frontend/dist/ s3://appkademy/

